"""generate table migrations

Revision ID: afc07b12f81a
Revises: 69d64e61e54a
Create Date: 2024-08-31 23:18:23.046807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc07b12f81a'
down_revision: Union[str, None] = '69d64e61e54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sekolah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npsn', sa.String(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npsn')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sekolah', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alamat_sekolah',
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('detail_tempat', sa.String(length=255), nullable=False),
    sa.Column('desa', sa.String(length=255), nullable=False),
    sa.Column('kecamatan', sa.String(length=255), nullable=False),
    sa.Column('kabupaten', sa.String(length=255), nullable=False),
    sa.Column('provinsi', sa.String(length=255), nullable=False),
    sa.Column('negara', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.PrimaryKeyConstraint('id_sekolah')
    )
    op.create_table('kepala_sekolah',
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('nip', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.PrimaryKeyConstraint('id_sekolah')
    )
    op.create_table('tahun_sekolah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sekolah', sa.Integer(), nullable=True),
    sa.Column('tahun', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dudi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_instansi_perusahaan', sa.String(length=255), nullable=False),
    sa.Column('bidang_usaha', sa.String(length=255), nullable=False),
    sa.Column('no_telepon', sa.String(length=12), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('id_tahun', sa.Integer(), nullable=False),
    sa.Column('tersedia', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_sekolah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_telepon')
    )
    op.create_table('guru_pembimbing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('no_telepon', sa.String(length=12), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('laki', 'perempuan', name='jeniskelaminenum'), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=255), nullable=False),
    sa.Column('tanggal_lahir', sa.String(), nullable=False),
    sa.Column('agama', sa.String(length=255), nullable=False),
    sa.Column('foto_profile', sa.String(), nullable=True),
    sa.Column('token_FCM', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('id_tahun', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_sekolah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip'),
    sa.UniqueConstraint('no_telepon')
    )
    op.create_table('jurusan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('id_tahun', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_sekolah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absen_jadwal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('tanggal_mulai', sa.Date(), nullable=True),
    sa.Column('tanggal_berakhir', sa.Date(), nullable=True),
    sa.Column('selisih_tanggal_day', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alamat_dudi',
    sa.Column('id_dudi', sa.Integer(), nullable=False),
    sa.Column('detail_tempat', sa.String(length=255), nullable=False),
    sa.Column('desa', sa.String(length=255), nullable=False),
    sa.Column('kecamatan', sa.String(length=255), nullable=False),
    sa.Column('kabupaten', sa.String(length=255), nullable=False),
    sa.Column('provinsi', sa.String(length=255), nullable=False),
    sa.Column('negara', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.PrimaryKeyConstraint('id_dudi')
    )
    op.create_table('alamat_guru_pembimbing',
    sa.Column('id_guru_pembimbing', sa.Integer(), nullable=False),
    sa.Column('detail_tempat', sa.String(length=255), nullable=False),
    sa.Column('desa', sa.String(length=255), nullable=False),
    sa.Column('kecamatan', sa.String(length=255), nullable=False),
    sa.Column('kabupaten', sa.String(length=255), nullable=False),
    sa.Column('provinsi', sa.String(length=255), nullable=False),
    sa.Column('negara', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_guru_pembimbing'], ['guru_pembimbing.id'], ),
    sa.PrimaryKeyConstraint('id_guru_pembimbing')
    )
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('tahun', sa.String(), nullable=False),
    sa.Column('id_jurusan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_jurusan'], ['jurusan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kouta_siswa',
    sa.Column('id_dudi', sa.Integer(), nullable=False),
    sa.Column('jumlah_pria', sa.Integer(), nullable=False),
    sa.Column('jumlah_wanita', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.PrimaryKeyConstraint('id_dudi'),
    sa.UniqueConstraint('id_dudi')
    )
    op.create_table('pembimbing_dudi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('no_telepon', sa.String(length=12), nullable=False),
    sa.Column('foto_profile', sa.String(), nullable=True),
    sa.Column('jenis_kelamin', sa.Enum('laki', 'perempuan', name='jeniskelaminenum'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('token_FCM', sa.String(), nullable=True),
    sa.Column('id_dudi', sa.Integer(), nullable=False),
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('id_tahun', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_sekolah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_telepon')
    )
    op.create_table('alamat_pembimbing_dudi',
    sa.Column('id_pembimbing_dudi', sa.Integer(), nullable=False),
    sa.Column('detail_tempat', sa.String(length=255), nullable=False),
    sa.Column('desa', sa.String(length=255), nullable=False),
    sa.Column('kecamatan', sa.String(length=255), nullable=False),
    sa.Column('kabupaten', sa.String(length=255), nullable=False),
    sa.Column('provinsi', sa.String(length=255), nullable=False),
    sa.Column('negara', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_pembimbing_dudi'], ['pembimbing_dudi.id'], ),
    sa.PrimaryKeyConstraint('id_pembimbing_dudi')
    )
    op.create_table('hari_absen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_jadwal', sa.Integer(), nullable=True),
    sa.Column('hari', sa.Enum('senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu', name='harienum'), nullable=True),
    sa.Column('batas_absen_masuk', sa.String(), nullable=True),
    sa.Column('batas_absen_pulang', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_jadwal'], ['absen_jadwal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kordinat_absen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('id_pembimbing_dudi', sa.Integer(), nullable=True),
    sa.Column('nama_tempat', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longtitude', sa.Float(), nullable=True),
    sa.Column('radius_absen_meter', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_pembimbing_dudi'], ['pembimbing_dudi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunjungan_guru_pembimbing_pkl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_guru_pembimbing', sa.Integer(), nullable=False),
    sa.Column('id_dudi', sa.Integer(), nullable=False),
    sa.Column('id_pembimbing_dudi', sa.Integer(), nullable=False),
    sa.Column('tanggal_kunjungan', sa.DateTime(), nullable=False),
    sa.Column('catatan', sa.String(length=1500), nullable=False),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_guru_pembimbing'], ['guru_pembimbing.id'], ),
    sa.ForeignKeyConstraint(['id_pembimbing_dudi'], ['pembimbing_dudi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis', sa.String(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('laki', 'perempuan', name='jeniskelaminenum'), nullable=False),
    sa.Column('no_telepon', sa.String(length=12), nullable=False),
    sa.Column('id_guru_pembimbing', sa.Integer(), nullable=False),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('id_pembimbing_dudi', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pkl', 'belum_pkl', 'menunggu', name='statuspklenum'), nullable=False),
    sa.Column('token_FCM', sa.String(), nullable=True),
    sa.Column('foto_profile', sa.String(), nullable=True),
    sa.Column('id_jurusan', sa.Integer(), nullable=False),
    sa.Column('id_kelas', sa.Integer(), nullable=False),
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('id_tahun', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_guru_pembimbing'], ['guru_pembimbing.id'], ),
    sa.ForeignKeyConstraint(['id_jurusan'], ['jurusan.id'], ),
    sa.ForeignKeyConstraint(['id_kelas'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['id_pembimbing_dudi'], ['pembimbing_dudi.id'], ),
    sa.ForeignKeyConstraint(['id_sekolah'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_sekolah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nis'),
    sa.UniqueConstraint('no_telepon')
    )
    op.create_table('absen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_absen_jadwal', sa.Integer(), nullable=True),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.String(), nullable=True),
    sa.Column('absen_masuk', sa.Time(), nullable=True),
    sa.Column('absen_pulang', sa.Time(), nullable=True),
    sa.Column('status_absen_masuk', sa.Enum('hadir', 'telat', 'tidak_hadir', 'izin', 'diluar_radius', name='statusabsenmasukkeluarenum'), nullable=True),
    sa.Column('status_absen_pulang', sa.Enum('hadir', 'telat', 'tidak_hadir', 'izin', 'diluar_radius', name='statusabsenmasukkeluarenum'), nullable=True),
    sa.Column('foto', sa.String(length=1500), nullable=True),
    sa.Column('status', sa.Enum('hadir', 'tidak_hadir', 'diluar_radius', name='statusabsenenum'), nullable=True),
    sa.ForeignKeyConstraint(['id_absen_jadwal'], ['absen_jadwal.id'], ),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alamat_siswa',
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('detail_tempat', sa.String(length=255), nullable=False),
    sa.Column('desa', sa.String(length=255), nullable=False),
    sa.Column('kecamatan', sa.String(length=255), nullable=False),
    sa.Column('kabupaten', sa.String(length=255), nullable=False),
    sa.Column('provinsi', sa.String(length=255), nullable=False),
    sa.Column('negara', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id_siswa')
    )
    op.create_table('laporan_pkl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('id_pembimbing_dudi', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('keterangan', sa.String(length=1500), nullable=True),
    sa.Column('file_laporan', sa.String(length=1500), nullable=True),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_pembimbing_dudi'], ['pembimbing_dudi.id'], ),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laporan_siswa_pkl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('topik_pekerjaan', sa.String(length=255), nullable=True),
    sa.Column('rujukan_kompetensi_dasar', sa.String(length=255), nullable=True),
    sa.Column('dokumentasi', sa.String(length=1500), nullable=True),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('id_pembimbing_dudi', sa.Integer(), nullable=True),
    sa.Column('id_guru_pembimbing', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=1500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_guru_pembimbing'], ['guru_pembimbing.id'], ),
    sa.ForeignKeyConstraint(['id_pembimbing_dudi'], ['pembimbing_dudi.id'], ),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengajuan_cancel_pkl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('proses', 'dibatalkan', 'setuju', 'tidak_setuju', name='statuscancelpklenum'), nullable=True),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengajuan_pkl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('id_dudi', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('proses', 'diterima', 'ditolak', 'dibatalkan', name='statuspengajuanenum'), nullable=True),
    sa.Column('waktu_pengajuan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_dudi'], ['dudi.id'], ),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('izin_absen_masuk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_absen', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=30000), nullable=True),
    sa.Column('status_izin', sa.Enum('izin', 'telat', 'diluar_radius', name='statusotherabsenenum'), nullable=True),
    sa.ForeignKeyConstraint(['id_absen'], ['absen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_absen')
    )
    op.create_table('izin_absen_pulang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_absen', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=30000), nullable=True),
    sa.Column('status_izin', sa.Enum('izin', 'telat', 'diluar_radius', name='statusotherabsenenum'), nullable=True),
    sa.ForeignKeyConstraint(['id_absen'], ['absen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_absen')
    )
    op.create_table('notification_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('id_pembimbing_dudi', sa.Integer(), nullable=True),
    sa.Column('id_guru_pembimbing', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_guru_pembimbing'], ['guru_pembimbing.id'], ),
    sa.ForeignKeyConstraint(['id_pembimbing_dudi'], ['pembimbing_dudi.id'], ),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_read')
    op.drop_table('izin_absen_pulang')
    op.drop_table('izin_absen_masuk')
    op.drop_table('pengajuan_pkl')
    op.drop_table('pengajuan_cancel_pkl')
    op.drop_table('notification')
    op.drop_table('laporan_siswa_pkl')
    op.drop_table('laporan_pkl')
    op.drop_table('alamat_siswa')
    op.drop_table('absen')
    op.drop_table('siswa')
    op.drop_table('kunjungan_guru_pembimbing_pkl')
    op.drop_table('kordinat_absen')
    op.drop_table('hari_absen')
    op.drop_table('alamat_pembimbing_dudi')
    op.drop_table('pembimbing_dudi')
    op.drop_table('kouta_siswa')
    op.drop_table('kelas')
    op.drop_table('alamat_guru_pembimbing')
    op.drop_table('alamat_dudi')
    op.drop_table('absen_jadwal')
    op.drop_table('jurusan')
    op.drop_table('guru_pembimbing')
    op.drop_table('dudi')
    op.drop_table('tahun_sekolah')
    op.drop_table('kepala_sekolah')
    op.drop_table('alamat_sekolah')
    op.drop_table('admin')
    op.drop_table('sekolah')
    op.drop_table('developer')
    # ### end Alembic commands ###
