from . import siswaModel
from . import sekolahModel
from . import developerModel
from . import dudiModel
from . import pembimbingDudiModel
from . import guruPembimbingModel
from . import laporanPklModel
from . import pengajuanPklModel
from . import notificationModel
from . import absenModel