name : build docker image

on :
  push : 
    branches : ["master"]

jobs :
  setUp :
    name : setUp app
    runs-on : ubuntu-24.04
    steps :
      - name : Check out the repo
        uses : actions/checkout@v3

      - name : install package
        run : sudo apt update -y && sudo apt install python3 software-properties-common pip postgresql-client curl -y && pip install poetry

      - name : cek python version
        run : python --version

      - name : "install depedencies"
        run : poetry lock --no-update && poetry install

      # - name : "testing connect db"
        # run : psql -h ${{ secrets.DB_HOST }} -p ${{ secrets.DB_PORT }} -U ${{ secrets.DB_USER }} <DB_NAME> -p ${{ secrets.DB_PASSWORD }}

      # - name : "update database url"
      #   run : sed -i 's/^DATABASE_URL=.*/DATABASE_URL=postgresql+asyncpg://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOSt }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}' .env

      - name : "run server"
        run : "uvicorn main:App --port 2008 --reload"
      
      - name : "test some endPoint"
        run : curl http://localhost:2008
  
  build-image-push :
    name : "build imsge and push image to docker registry"
    runs-on : ubuntu-latest
    needs : [setUp]
    steps :
      - name : Check out the repo
        uses : actions/checkout@v3

      - name : Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: "."
          push: true
          tags: arlianasrori/simonPkl:latest